extends:
  - airbnb-typescript
  - plugin:import/typescript
  - "plugin:@typescript-eslint/recommended"
parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es6: true
  jest: true
plugins:
  - import
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  import/extensions: 0
  import/no-unresolved: 0
