extends:
  - airbnb-typescript
  - plugin:import/typescript
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es6: true
  jest: true
plugins:
  - import
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  consistent-return: 0
  prefer-const: 0
  import/extensions: 0
  import/no-unresolved: 0
  react/jsx-one-expression-per-line: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  import/prefer-default-export: 0
  "@typescript-eslint/explicit-function-return-type": 0
