name: deploy

on: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: netlify/actions/cli@master
      args: deploy
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
